language: ruby
rvm:
  - 2.5
script: bundle exec jekyll build

branches:
  only:
  - travis

deploy:
  provider: script
  skip_cleanup: true
  script: ruby scripts/deploy.rb
  keep_history: true
  on:
    branch: travis