language: ruby
rvm:
  - 2.5
script: bundle exec jekyll build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master

# deploy:
#   provider: script
#   script: bash scripts/deploy.sh
#   on:
#     branch: develop